#服务端口
server:
  port: 9998
spring:
  application:
    #服务名
    name: service-edu
    #mysql数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_edu?serverTimezone=GMT%2B8
    username: root
    password: 5041235
  profiles:
    #环境设置:dev、test、prod
    active: dev
  jackson:
    #设置时区
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

#mybatis日志
mybatis-plus:
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:com/luobo/eduservice/mapper/xml/*.xml


#开启熔断器机制
feign:
  hystrix:
    enabled: true
